### ISSUE TITLE
MacOS 10.9.5 throw error when input string

### ISSUE THREAD

**Issue by futurist** [zaaack/ELaunch#11]
MacOS 10.9.5, Elaunch 0.0.2, launch for first time and Toggle Elaunch window, input any string, will throw below error:

```
Uncaught Exception:
Error: watch /Users/z/Applications ENOENT
    at exports._errnoException (util.js:949:11)
    at FSWatcher.start (fs.js:1433:19)
    at Object.fs.watch (fs.js:1460:11)
    at pluginConfig.app_path.forEach (/Applications/ELaunch.app/Contents/Resources/app.asar/plugins/app/darwin/index.js:56:25)
    at Array.forEach (native)
    at init (/Applications/ELaunch.app/Contents/Resources/app.asar/plugins/app/darwin/index.js:55:25)
    at Object.setConfig (/Applications/ELaunch.app/Contents/Resources/app.asar/plugins/app/darwin/index.js:77:5)
    at Object.exec (/Applications/ELaunch.app/Contents/Resources/app.asar/plugins/index.js:61:32)
    at EventEmitter.ipcMain.on (/Applications/ELaunch.app/Contents/Resources/app.asar/index.js:36:12)
    at emitTwo (events.js:106:13)
```

After first time indexing finished, the error will not show again. But will appear for the next time launch.

**Comment by zaaack** [comment]
好吧，我看出bug原因了。well，I see

**Comment by zaaack** [comment]
主分支已经修复了，可以手动编译一下。。

**Comment by zaaack** [comment]
https://github.com/zaaack/ELaunch/releases/tag/v0.0.3
