### ISSUE TITLE
报错了，把第17行注释掉可以启动，但是也太卡了吧..

### ISSUE THREAD

**Issue by imzhi** [zaaack/ELaunch#2]
```
yxz@yxz-Aspire-4743:~/pproject/nodejs/ELaunch$ npm start

> ELaunch@0.0.1 start /home/yxz/pproject/nodejs/ELaunch
> electron ./index.js

App threw an error during load
TypeError: Cannot read property 'hide' of undefined
    at init (/home/yxz/pproject/nodejs/ELaunch/index.js:17:11)
    at Object.<anonymous> (/home/yxz/pproject/nodejs/ELaunch/index.js:136:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at loadApplicationPackage (/home/yxz/pproject/nodejs/ELaunch/node_modules/.npminstall/electron-prebuilt/1.2.5/electron-prebuilt/dist/resources/default_app.asar/main.js:259:12)
    at Object.<anonymous> (/home/yxz/pproject/nodejs/ELaunch/node_modules/.npminstall/electron-prebuilt/1.2.5/electron-prebuilt/dist/resources/default_app.asar/main.js:301:5)
    at Module._compile (module.js:541:32)
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property 'hide' of undefined
    at init (/home/yxz/pproject/nodejs/ELaunch/index.js:17:11)
    at Object.<anonymous> (/home/yxz/pproject/nodejs/ELaunch/index.js:136:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at loadApplicationPackage (/home/yxz/pproject/nodejs/ELaunch/node_modules/.npminstall/electron-prebuilt/1.2.5/electron-prebuilt/dist/resources/default_app.asar/main.js:259:12)
    at Object.<anonymous> (/home/yxz/pproject/nodejs/ELaunch/node_modules/.npminstall/electron-prebuilt/1.2.5/electron-prebuilt/dist/resources/default_app.asar/main.js:301:5)
    at Module._compile (module.js:541:32)
```

启动后，提示正在建立索引，实际上程序是失去响应的状态了，输入什么完全没反应

![screenshot from 2016-06-26 08 18 37](https://cloud.githubusercontent.com/assets/2304019/16359820/c47cd856-3b76-11e6-95dc-04d8831d563d.png)

`Ctrl+C` 强制结束之后，菜单栏上的小图标还在...
![screenshot from 2016-06-26 08 21 34](https://cloud.githubusercontent.com/assets/2304019/16359826/04a69c3c-3b77-11e6-8c27-1faba794276c.png)

**Comment by zaaack** [comment]
稍等～～

**Comment by zaaack** [comment]
@imzhi  你再试试看？

**Comment by zaaack** [comment]
@imzhi  默认配置的app_path有的系统可能不存在。现在试试看？报错了才会卡住。。没报错的话其实性能还可以的。。

**Comment by zaaack** [comment]
#642871c2c26e7d71ec22b77242513265e187cbe0

**Comment by imzhi** [comment]
更新了，可以用了。创建索引还是挺快的，大概1、2分钟就好，机器比较老

**Comment by zaaack** [comment]
@imzhi 1其实创建的索引不是文件的索引，是应用的索引，而真正耗时的部分却是搜索图标。。
